# Generated by Django 4.2.3 on 2024-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
            ],
        ),
    ]
