# Generated by Django 4.2.3 on 2024-02-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresso_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('otp', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
