# Generated by Django 4.2.3 on 2024-03-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progresso_db', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='date',
        ),
    ]
